### ISSUE TITLE
No access to agribot_navigation

### ISSUE THREAD

**Issue by joao-pm-santos96** [alirezaahmadi/AgriBot-Local-Planner#1]
Hi @alirezaahmadi !

In the README, a package called **[agribot_navigation](https://gitlab.igg.uni-bonn.de/nived/mp-agribot/blob/master/doc/api/agribot_navigation.md)** is mentioned, but it seams to be in some private server... can you please make it public or, even better, make the _params_ folder + files avaiable in this repo?

Thank you.

**Comment by alirezaahmadi** [comment]
Hi, 

Currently I am in a workshop, will try to update it in a few days. 

Best
Alireza Ahmadi
Research Assistant and Doctoral student
Department of Agricultural Robotics and Engineering
PhenoRob (Cluster of Excellence)
University of Bonn
Nussallee 5, 53115 Bonn, Germany
Tel: +49-(0)288-73-4602
Email: ***@***.***
